repos:
  # Basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: pretty-format-json
        args: [--autofix]
        exclude: backend/.vscode

  # Ruff using Poetry virtualenv
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: /media/eugene/Maxtor1/openapi_project/simpsonapi_playground/backend/.venv/bin/ruff
        args: [check, --fix, --no-cache]
        language: system
        types: [python]

  # Mypy using Poetry virtualenv
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: /media/eugene/Maxtor1/openapi_project/simpsonapi_playground/backend/.venv/bin/mypy
        pass_filenames: false
        args:
          - backend/simpsonapi_playground
          - backend/tests
        language: system
        types: [python]
